import type { DashboardDoc } from "./dashboard-types";

export const defaultDashboard: DashboardDoc = {
  widgets: [
    {
      id: "treemap-tech",
      type: "treemap",
      title: "科技 Tech",
      status: "ok",
      updatedAt: "12m ago",
      config: { group: "tech" },
    },
    {
      id: "treemap-markets",
      type: "treemap",
      title: "市场 Markets",
      status: "ok",
      updatedAt: "8m ago",
      config: { group: "markets" },
    },
    {
      id: "treemap-geo",
      type: "treemap",
      title: "地缘 Geo",
      status: "ok",
      updatedAt: "16m ago",
      config: { group: "geo" },
    },
    {
      id: "feed-signals",
      type: "feed",
      title: "Signals",
      status: "ok",
      updatedAt: "2m ago",
      config: { variant: "signals" },
    },
    {
      id: "feed-rss",
      type: "feed",
      title: "Feeds",
      status: "ok",
      updatedAt: "5m ago",
      config: { variant: "rss" },
    },
    {
      id: "ts-watchlist",
      type: "timeseries",
      title: "Watchlist",
      status: "ok",
      updatedAt: "3m ago",
      config: { variant: "watchlist" },
    },
    {
      id: "ts-sentiment",
      type: "timeseries",
      title: "Global Sentiment",
      status: "ok",
      updatedAt: "10m ago",
      config: { variant: "sentiment" },
    },
    {
      id: "embed-live",
      type: "embed",
      title: "Live Monitor",
      status: "ok",
      updatedAt: "now",
      config: { src: "https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8", mode: "video" },
    },
  ],
  layout: {
    lg: [
      { i: "treemap-tech", x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets", x: 4, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo", x: 8, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "feed-signals", x: 0, y: 3, w: 3, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss", x: 3, y: 3, w: 3, h: 3, minW: 2, minH: 2 },
      { i: "ts-watchlist", x: 6, y: 3, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "ts-sentiment", x: 9, y: 3, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "embed-live", x: 6, y: 5, w: 6, h: 2, minW: 3, minH: 2 },
    ],
    md: [
      { i: "treemap-tech", x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets", x: 4, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo", x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "feed-signals", x: 4, y: 3, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss", x: 0, y: 6, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "ts-watchlist", x: 4, y: 6, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "ts-sentiment", x: 0, y: 9, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "embed-live", x: 4, y: 9, w: 4, h: 2, minW: 3, minH: 2 },
    ],
    sm: [
      { i: "treemap-tech", x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets", x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo", x: 0, y: 6, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "feed-signals", x: 0, y: 9, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss", x: 0, y: 12, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "ts-watchlist", x: 0, y: 15, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "ts-sentiment", x: 0, y: 17, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "embed-live", x: 0, y: 19, w: 4, h: 2, minW: 3, minH: 2 },
    ],
  },
};
