import type { DashboardDoc } from "./dashboard-types";

export const defaultDashboard: DashboardDoc = {
  widgets: [
    // ── Treemaps ──
    {
      id: "treemap-tech",
      type: "treemap",
      title: "科技 Tech",
      status: "ok",
      updatedAt: "12m ago",
      config: { group: "tech" },
    },
    {
      id: "treemap-markets",
      type: "treemap",
      title: "市场 Markets",
      status: "ok",
      updatedAt: "8m ago",
      config: { group: "markets" },
    },
    {
      id: "treemap-geo",
      type: "treemap",
      title: "地缘 Geo",
      status: "ok",
      updatedAt: "16m ago",
      config: { group: "geo" },
    },
    // ── Feeds ──
    {
      id: "feed-signals",
      type: "feed",
      title: "Signals",
      status: "ok",
      updatedAt: "2m ago",
      config: { variant: "signals" },
    },
    {
      id: "feed-rss",
      type: "feed",
      title: "RSS Feeds",
      status: "ok",
      updatedAt: "5m ago",
      config: { variant: "rss" },
    },
    // ── Timeseries ──
    {
      id: "ts-global",
      type: "timeseries",
      title: "全球趋势 Global Trend",
      status: "ok",
      updatedAt: "10m ago",
      config: { variant: "sentiment" },
    },
    {
      id: "ts-watchlist",
      type: "timeseries",
      title: "Watchlist",
      status: "ok",
      updatedAt: "3m ago",
      config: { variant: "watchlist" },
    },
    // ── Countdowns ──
    {
      id: "countdown-events",
      type: "countdown",
      title: "行业事件 Events",
      status: "ok",
      updatedAt: "now",
      config: {
        label: "行业事件",
        showSeconds: true,
        targets: [
          {
            id: "evt-1",
            title: "Apple WWDC 2026",
            target: "2026-06-09T17:00:00Z",
            source: "manual",
            keyword: "Apple WWDC",
          },
          {
            id: "evt-2",
            title: "NVIDIA GTC 2026",
            target: "2026-03-17T16:00:00Z",
            source: "manual",
            keyword: "NVIDIA GTC",
          },
          {
            id: "evt-3",
            title: "FOMC 利率决议",
            target: "2026-07-29T18:00:00Z",
            source: "manual",
            keyword: "FOMC",
          },
        ],
      },
    },
    {
      id: "countdown-earnings",
      type: "countdown",
      title: "财报季 Earnings",
      status: "ok",
      updatedAt: "now",
      config: {
        label: "财报季",
        showSeconds: true,
        targets: [
          {
            id: "ern-1",
            title: "NVIDIA Q2 Earnings",
            target: "2026-08-27T20:00:00Z",
            source: "manual",
            keyword: "NVIDIA earnings",
          },
          {
            id: "ern-2",
            title: "Apple Q3 Earnings",
            target: "2026-07-30T20:00:00Z",
            source: "manual",
            keyword: "Apple earnings",
          },
          {
            id: "ern-3",
            title: "Microsoft Q4 Earnings",
            target: "2026-07-22T20:00:00Z",
            source: "manual",
            keyword: "Microsoft earnings",
          },
        ],
      },
    },
    // ── Utility ──
    {
      id: "weather-sh",
      type: "weather",
      title: "天气 Weather",
      status: "ok",
      updatedAt: "30m ago",
      config: { unit: "C", lat: 31.23, lon: 121.47 },
    },
    {
      id: "stat-sp500",
      type: "stat",
      title: "S&P 500",
      status: "ok",
      updatedAt: "1m ago",
      config: {
        value: "5,842.31",
        label: "S&P 500",
        symbol: "USD",
        trend: "up",
        change: "+1.2%",
        mode: "manual",
      },
    },
    {
      id: "clock-world",
      type: "clock",
      title: "时钟 Clock",
      status: "ok",
      updatedAt: "now",
      config: {},
    },
    // ── Player ──
    {
      id: "embed-live",
      type: "embed",
      title: "Live Monitor",
      status: "ok",
      updatedAt: "now",
      config: {
        src: "https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8",
        mode: "video",
      },
    },
  ],
  layout: {
    lg: [
      // Row 0-2: 3 treemaps
      { i: "treemap-tech",      x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets",   x: 4, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo",       x: 8, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      // Row 3-4: signals + rss + trend + watchlist
      { i: "feed-signals",      x: 0, y: 3, w: 3, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss",          x: 3, y: 3, w: 3, h: 3, minW: 2, minH: 2 },
      { i: "ts-global",         x: 6, y: 3, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "ts-watchlist",      x: 9, y: 3, w: 3, h: 2, minW: 2, minH: 2 },
      // Row 5-6: countdowns + weather + stat
      { i: "countdown-events",  x: 0, y: 6, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "countdown-earnings", x: 4, y: 6, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "weather-sh",        x: 8, y: 5, w: 2, h: 2, minW: 2, minH: 2 },
      { i: "stat-sp500",        x: 10, y: 5, w: 2, h: 2, minW: 2, minH: 2 },
      // Row 7-8: clock + player
      { i: "clock-world",       x: 0, y: 8, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "embed-live",        x: 3, y: 8, w: 9, h: 2, minW: 3, minH: 2 },
    ],
    md: [
      { i: "treemap-tech",      x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets",   x: 4, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo",       x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "feed-signals",      x: 4, y: 3, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss",          x: 0, y: 6, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "ts-global",         x: 4, y: 6, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "ts-watchlist",      x: 0, y: 9, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "countdown-events",  x: 4, y: 9, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "countdown-earnings", x: 0, y: 11, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "weather-sh",        x: 4, y: 11, w: 2, h: 2, minW: 2, minH: 2 },
      { i: "stat-sp500",        x: 6, y: 11, w: 2, h: 2, minW: 2, minH: 2 },
      { i: "clock-world",       x: 0, y: 13, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "embed-live",        x: 4, y: 13, w: 4, h: 2, minW: 3, minH: 2 },
    ],
    sm: [
      { i: "treemap-tech",      x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-markets",   x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "treemap-geo",       x: 0, y: 6, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "feed-signals",      x: 0, y: 9, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "feed-rss",          x: 0, y: 12, w: 4, h: 3, minW: 2, minH: 2 },
      { i: "ts-global",         x: 0, y: 15, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "ts-watchlist",      x: 0, y: 17, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "countdown-events",  x: 0, y: 19, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "countdown-earnings", x: 0, y: 21, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "weather-sh",        x: 0, y: 23, w: 2, h: 2, minW: 2, minH: 2 },
      { i: "stat-sp500",        x: 2, y: 23, w: 2, h: 2, minW: 2, minH: 2 },
      { i: "clock-world",       x: 0, y: 25, w: 4, h: 2, minW: 2, minH: 2 },
      { i: "embed-live",        x: 0, y: 27, w: 4, h: 2, minW: 3, minH: 2 },
    ],
  },
};
